export const CATEGORIES_ACTION_TYPES = {
  GET_CATEGORIES_START: 'categories/GET_CATEGORIES_START',
  GET_CATEGORIES_SUCCESS: 'categories/GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAILURE:  'categories/GET_CATEGORIES_FAILURE',
};
  
